name: backup

on:
  push:
    branches:
      - main

jobs:
  repo-metadata:
    runs-on: ubuntu-latest
    name: "Backup Repo Metadata"
    permissions:
      contents: write
      actions: read
      attestations: read
      checks: read
      contents: read
      deployments: read
      id-token: write|none
      issues: read
      models: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      security-events: read
      statuses: read

    steps:
      - uses: actions/checkout@v4

      - name: "Install backup-github-repo"
        run: npm install -g backup-github-repo

      - name: "Configure backup-github-repo"
        run: echo "{\"token\":\"${GH_TOKEN}\"}" > .backup-github-repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run backup-github-repo"
        run: backup-github-repo

      - name: "Push the results"
        run: |
          git config --global user.name 'Backup Job'
          git config --global user.email 'taskwarrior@noreply.github.com'
          git commit -am "Update Repo Backup"
          git push
